### ISSUE TITLE
Workbox Error: One of the glob patterns doesn't match any files

### ISSUE THREAD

**Issue by Darkside73** [nuxt-community/modules#110]
During the production build I'm getting following error:
```
Error: One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/home/projects/frontend/.nuxt/dist",
  "globPattern": "**/*.{js,css}",
  "globIgnores": [
    "node_modules/**/*",
    "../../static/workbox-sw.prod.v1.1.0.js",
    "../../static/sw.js"
  ]
}
    at module.exports.err (/home/projects/frontend/node_modules/workbox-build/build/lib/utils/get-file-details.js:20:11)
    at globPatterns.reduce (/home/projects/frontend/node_modules/workbox-build/build/lib/get-file-manifest-entries.js:107:32)
    at Array.reduce (native)
    at getFileManifestEntries (/home/projects/frontend/node_modules/workbox-build/build/lib/get-file-manifest-entries.js:106:36)
    at copyWorkboxSW.then.then (/home/projects/frontend/node_modules/workbox-build/build/lib/generate-sw.js:142:12)
```
Deps:
```
├─ @nuxtjs/cssnano@1.0.1
├─ @nuxtjs/google-analytics@1.0.0
├─ @nuxtjs/icon@1.0.0
├─ @nuxtjs/manifest@1.6.1
├─ @nuxtjs/meta@1.2.1
├─ @nuxtjs/optimize@1.1.0
├─ @nuxtjs/pwa@0.2.0
├─ @nuxtjs/workbox@1.1.4
├─ nuxt@1.0.0-rc3
```

**Comment by Darkside73** [comment]
It's strange. The issue is in that ```globalPattern``` option without ```s``` on the end. But latest ```@nuxtjs/workbox``` has correct spelling...

**Comment by pi0** [comment]
This should be fixed with `@nuxtjs/workbox:^1.1.5` please upgrade :)

**Comment by Darkside73** [comment]
Exact same error with @nuxtjs/workbox 1.1.6 and nuxt 1.0.0-rc4

**Comment by pi0** [comment]
Yep i can confirm that annoying bug too :( We should set a prize for who finds the main cause :D (I guess it is a deep race condition in webpack plugins executation)

**Comment by pi0** [comment]
@Darkside73 Please verify with `1.2.0` I've changed workbox webpack with a native nuxt plugin to prevent such race conditions.

**Comment by Darkside73** [comment]
Yes. Build has finished without any errors. Thanks)

**Comment by MtDalPizzol** [comment]
Hi... I'm having this issue with Nuxt 1.4.1:

```
Error: One of the glob patterns doesn't match any files. Please remove or fix the following: {
    "globDirectory": "/home/dalpizzol/Dev/projects/riffnailer/riffnailer-pwa/.nuxt/dist",
    "globPattern": "**/*.{webp}",
    "globIgnores": [
      "node_modules/**/*"
    ]
  }
```
