### ISSUE TITLE
@nuxt/toast - usage error

### ISSUE THREAD

**Issue by mahesh29** [nuxt-community/modules#150]
Hi there,

I am using the built-in toast capability of nuxt (1.0.0-rc4)
I encountered this problem where `inject` seems to be undefined on the [line](https://github.com/nuxt-community/modules/blob/bf7067f519ab4f038687ce0236f9e960db9932f5/modules/toast/plugin.js#L7)

```
export default function (ctx, inject) {
  inject('toast', Vue.toasted)
}
```

My nuxt.config.js looks like the follows:
```
.
.
.
 modules: [
    '@nuxtjs/toast'
  ],
  toast: {
    position: 'center'
  }
.
.
```

When i run `npm run dev`, and the page loads up on localhost.
I get the following error:
```
VM4071 app.js:630 [nuxt] Error while initializing app TypeError: inject is not a function
    at webpackJsonp.295.__webpack_exports__.a (http://localhost:8000/_nuxt/webpack:/.nuxt/toast.js:9:1)
    at _callee$ (http://localhost:8000/_nuxt/webpack:/.nuxt/index.js:40:1)
    at tryCatch (http://localhost:8000/_nuxt/webpack:/node_modules/regenerator-runtime/runtime.js:65:1)
    at Generator.invoke [as _invoke] (http://localhost:8000/_nuxt/webpack:/node_modules/regenerator-runtime/runtime.js:299:1)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/_nuxt/webpack:/node_modules/regenerator-runtime/runtime.js:117:1)
    at step (http://localhost:8000/_nuxt/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at http://localhost:8000/_nuxt/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1
    at Promise (<anonymous>)
    at F (http://localhost:8000/_nuxt/webpack:/node_modules/core-js/library/modules/_export.js:35:1)
    at http://localhost:8000/_nuxt/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1
```

I would like to understand, if i have configured this right, if i have, I dont quite get why the `inject` method is `undefined`.

Any help would be appreciated!

Best,
Mahesh 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c91">#c91</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Please upgrade nuxt to latest RC.(11) and it will be working :)

**Comment by mahesh29** [comment]
Actually I was experiencing an issue with 3rd party libs not loading up for the versions after RC4, hence I was using RC4

I will give RC11 a shot and see how things go. Thanks for the help 😊

-Mahesh
