### ISSUE TITLE
@nuxt.js/axios - 502 response on the first load

### ISSUE THREAD

**Issue by lavsurgut** [nuxt-community/modules#67]
I'm calling axios in the asyncData like so: 
``
const {data} = await context.app.$axios.get('https://api.url')
``
Getting error on the first page load. In case I'm accessing it again or route push to another page with the same request - it works.

Here is the error log:
```
 @nuxtjs/axios Request:
 { adapter: [Function: httpAdapter],
   transformRequest: { '0': [Function: transformRequest] },
   transformResponse: { '0': [Function: transformResponse] },
   timeout: 0,
   xsrfCookieName: 'XSRF-TOKEN',
   xsrfHeaderName: 'X-XSRF-TOKEN',
   maxContentLength: -1,
   validateStatus: [Function: validateStatus],
   headers:
    { common: { Accept: 'application/json, text/plain, */*' },
      delete: {},
      get: {},
      head: {},
      post: { 'Content-Type': 'application/x-www-form-urlencoded' },
      put: { 'Content-Type': 'application/x-www-form-urlencoded' },
      patch: { 'Content-Type': 'application/x-www-form-urlencoded' },
      host: 'orno.space:3001',
      connection: 'keep-alive',
      'cache-control': 'max-age=0',
      'upgrade-insecure-requests': '1',
      'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
      accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
      referer: 'http://orno.space:3001/',
      'accept-encoding': 'gzip, deflate, sdch',
      'accept-language': 'en-US,en;q=0.8',
      cookie: 'G_ENABLED_IDPS=google; fblo_981497855289707=y; modernizr={"flexbox":true}',
      'if-none-match': 'W/"380a1-tncBOgy3/aUyzxkcmHX8rAxeYsA"' },
   baseURL: 'https://backend.orno.space/wp-json/',
   method: 'get',
   url: 'https://backend.orno.space/wp-json/cs-rest-api/v1/job' }
 [@nuxtjs/axios] Error:
 { Error: Request failed with status code 502
     at createError (/var/www/frontend-2/node_modules/axios/lib/core/createError.js:15:15)
     at settle (/var/www/frontend-2/node_modules/axios/lib/core/settle.js:18:12)
     at IncomingMessage.handleStreamEnd (/var/www/frontend-2/node_modules/axios/lib/adapters/http.js:186:11)
     at emitNone (events.js:91:20)
     at IncomingMessage.emit (events.js:188:7)
     at endReadableNT (_stream_readable.js:975:12)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
   config:
    { adapter: [Function: httpAdapter],
      transformRequest: { '0': [Function: transformRequest] },
      transformResponse: { '0': [Function: transformResponse] },
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus],
      headers:
       { Accept: 'application/json, text/plain, */*',
         host: 'orno.space:3001',
         connection: 'keep-alive',
         'cache-control': 'max-age=0',
         'upgrade-insecure-requests': '1',
         'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
         accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
         referer: 'http://orno.space:3001/',
         'accept-encoding': 'gzip, deflate, sdch',
         'accept-language': 'en-US,en;q=0.8',
         cookie: 'G_ENABLED_IDPS=google; fblo_981497855289707=y; modernizr={"flexbox":true}',
         'if-none-match': 'W/"380a1-tncBOgy3/aUyzxkcmHX8rAxeYsA"' },
      baseURL: 'https://backend.orno.space/wp-json/',
      method: 'get',
      url: 'https://backend.orno.space/wp-json/cs-rest-api/v1/job',
      withCredentials: true,
      data: undefined },
   response:
    { status: 502,
      statusText: 'Bad Gateway',
      headers:
       { server: 'nginx',
         date: 'Mon, 17 Jul 2017 09:38:28 GMT',
         'content-type': 'text/html; charset=UTF-8',
         'content-length': '568',
         connection: 'keep-alive' },
      config:
       { adapter: [Function: httpAdapter],
         transformRequest: [Object],
         transformResponse: [Object],
         timeout: 0,
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus],
         headers: [Object],
         baseURL: 'https://backend.orno.space/wp-json/',
         method: 'get',
         url: 'https://backend.orno.space/wp-json/cs-rest-api/v1/job',
         withCredentials: true,
         data: undefined },
      request:
       Writable {
         _writableState: [Object],
         writable: true,
         domain: null,
         _events: [Object],
         _eventsCount: 2,
         _maxListeners: undefined,
         _options: [Object],
         _redirectCount: 0,
         _onNativeResponse: [Function],
         _currentRequest: [Object],
         _currentUrl: 'https://backend.orno.space' }}
```

**Comment by silverbackdan** [comment]
I'd have thought if you are getting a response from the server (which you are as you'll see the headers being returned appear to be from your nginx server) you may find more information in your server logs about the error. Have you checked there?

**Comment by pi0** [comment]
Please reopen a new issue in [axios-module](https://github.com/nuxt-community/axios-module) repo if problem still exits.
