### ISSUE TITLE
[cssnano/pwa] Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by romualdr** [nuxt-community/modules#98]
## Expected Behavior

Running `yarn dev` should not trigger any error on a fresh install.

## Actual Behavior

Running `yarn dev` triggers an error `TypeError: Cannot read property 'push' of undefined`

![image](https://user-images.githubusercontent.com/5497356/28715517-a7425102-7398-11e7-854f-ef199b2c8517.png)

## Stacktrace

```
TypeError: Cannot read property 'push' of undefined
    at ModuleContainer.nuxtCssano (/Users/romuald/Private/base-backoffice/node_modules/@nuxtjs/cssnano/index.js:4:29)
    at /Users/romuald/Private/base-backoffice/node_modules/nuxt/lib/core/module.js:133:29
    at Promise (<anonymous>)
    at ModuleContainer._callee2$ (/Users/romuald/Private/base-backoffice/node_modules/nuxt/lib/core/module.js:132:12)
    at tryCatch (/Users/romuald/Private/base-backoffice/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/romuald/Private/base-backoffice/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/romuald/Private/base-backoffice/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/romuald/Private/base-backoffice/node_modules/nuxt/dist/nuxt.js:852:30)
    at /Users/romuald/Private/base-backoffice/node_modules/nuxt/dist/nuxt.js:863:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[nuxt] Unhandled promise rejection: TypeError: Cannot read property 'push' of undefined
```

## Steps to Reproduce the Problem

  1. `vue init nuxt-community/pwa my-app`
  2. `cd my-app`
  3. `yarn install`
  4. `yarn dev`

## Specifications

  - Version: Nuxt version "1.0.0-rc3" - Vue CLI: 2.8.2
  - Platform: macOS Sierra 10.12.5

**Comment by silverbackdan** [comment]
It seems `this.options.build.postcss` is now undefined
https://github.com/nuxt-community/modules/blob/master/modules/cssnano/index.js#L4

`options` is coming back as
```js
{ performance: { gzip: false },
  head: 
   { titleTemplate: '%s - Starter Website',
     meta: [ [Object], [Object] ],
     link: [ [Object] ],
     style: [],
     script: [] },
  loading: '~components/PageLoader.vue',
  css: [ '~assets/sass/main.sass' ],
  build: 
   { vendor: [ 'lodash', 'axios' ],
     extend: [Function: extend],
     analyze: false,
     extractCSS: false,
     ssr: 
      { cache: 
         LRUCache {
           max: 10000,
           maxAge: 900000
         } },
     publicPath: '/_nuxt/',
     filenames: 
      { css: 'common.[chunkhash].css',
        manifest: 'manifest.[hash].js',
        vendor: 'vendor.bundle.[chunkhash].js',
        app: 'nuxt.bundle.[chunkhash].js' },
     plugins: [ [Object], [Object], [Object] ],
     babel: {},
     postcss: undefined,
     templates: [ [Object] ],
     watch: [],
     devMiddleware: {},
     hotMiddleware: {} },
  cache: true,
  plugins: 
   [ { src: '/Volumes/LaCie/GitHub/nuxt-express-symfony/.nuxt/workbox.plugin.33bce3ec.js',
       ssr: false },
     { src: '~plugins/VueCookie', ssr: false } ],
  router: 
   { middleware: [ 'session' ],
     extendRoutes: [Function: extendRoutes],
     mode: 'history',
     base: '/',
     routes: [],
     linkActiveClass: 'nuxt-link-active',
     linkExactActiveClass: 'nuxt-link-exact-active',
     scrollBehavior: null,
     fallback: false },
  modules: 
   [ '@nuxtjs/component-cache',
     [ '@nuxtjs/pwa', [Object] ],
     [ '@nuxtjs/axios', [Object] ],
     [ '@nuxtjs/google-analytics', [Object] ] ],
  manifest: 
   { name: 'BW Starter Website',
     short_name: 'BWStarter',
     description: 'A starter de-coupled front-end/back-end website with common functionality including an admin login',
     lang: 'en',
     background_color: '#FFFFFF',
     theme_color: '#4770fb',
     icons: [ [Object], [Object], [Object] ],
     start_url: '/',
     display: 'standalone' },
  rootDir: '/Volumes/LaCie/GitHub/nuxt-express-symfony',
  dev: false,
  mode: 'universal',
  buildDir: '/Volumes/LaCie/GitHub/nuxt-express-symfony/.nuxt',
  nuxtAppDir: '/Volumes/LaCie/GitHub/nuxt-express-symfony/node_modules/nuxt/lib/app',
  generate: 
   { dir: 'dist',
     routes: [],
     concurrency: 500,
     interval: 0,
     minify: 
      { collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        minifyCSS: true,
        minifyJS: true,
        processConditionalComments: true,
        removeAttributeQuotes: false,
        removeComments: false,
        removeEmptyAttributes: true,
        removeOptionalTags: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: false,
        removeStyleLinkTypeAttributes: false,
        removeTagWhitespace: false,
        sortAttributes: true,
        sortClassName: true,
        trimCustomFragments: true,
        useShortDoctype: true } },
  env: {},
  layouts: {},
  serverMiddleware: [],
  ErrorPage: null,
  transition: { name: 'page', mode: 'out-in' },
  render: 
   { bundleRenderer: {},
     resourceHints: true,
     ssr: true,
     http2: { push: false },
     static: {},
     gzip: { threshold: 0 },
     etag: { weak: true } },
  watchers: { webpack: {}, chokidar: {} },
  srcDir: '/Volumes/LaCie/GitHub/nuxt-express-symfony',
  appTemplatePath: '/Volumes/LaCie/GitHub/nuxt-express-symfony/.nuxt/views/app.template.html',
  store: true }
```
I imagine it was an empty array before. Must be latest Nuxt RC. Depending on the next release date for now a hack is:
```js
module.exports = function nuxtCssano(options) {
  if (this.options.build.postcss === undefined) {
    this.options.build.postcss = []
  }
  this.options.build.postcss.push(cssnano(options))
}
```

**Comment by silverbackdan** [comment]
OR much smarter option is to define it in your nuxt.config.js
```js
build: {
    postcss: []
}
```

**Comment by pi0** [comment]
Sorry for inconveniences during rc3 upgrade. cssnano 1.0.1 now works well with `rc3`

**Comment by bdebever** [comment]
The issue persists on my side. Any idea how to solve it?

**Comment by pi0** [comment]
@bdebever Please make sure `1.0.1` is installed by checking `node_modules/cssnano/package.json`

**Comment by bdebever** [comment]
Yes it is :/

**Comment by pi0** [comment]
@bdebever It is working fine with a clean `rc3` setup. (https://glitch.com/edit/#!/nuxt-pwa) We can't help unless having a clear idea about your project's problem. Please provide exact error about your current "issues"

**Comment by bayssmekanique** [comment]
@bdebever, try running `npm install @nuxtjs/cssnano@latest`.  This will update your `package.json` and `package-lock.json` files and move them to `^1.0.1` (as of 8/2/17).

**Comment by gfriend-malaysia** [comment]
in rc8 i still have this problem even i have put this
build: {
    postcss: []
}
and also i also tried npm install @nuxtjs/cssnano@latest
but it break my whole app, any idea how to solve it?

**Comment by pi0** [comment]
Thanks for the report. Actually with rc6+ cssnano is enabled vy default. I'll reopen until release the patch.

**Comment by pi0** [comment]
Hmm seems cssnano was already disabled with workbox! @gfriend-malaysia Would you please upgrade to latest version on pwa?

**Comment by gfriend-malaysia** [comment]
@pi0 after upgrade to latest version of @nuxtjs/pwa the error have resolve, Thank you and appreciate your help 👍
